app/app.py
import json, os

from collections import OrderedDict

from flask import Flask, render_template, send_from_directory

from blueprints import auth, examples, evaluation

def create_app():
    app = Flask('syneval', instance_relative_config=True)

    # load configuration
    with open('config.json', 'r', encoding='utf8') as fop:
        config = json.load(fop, object_pairs_hook=OrderedDict)
    app.config.update(config)

    # add data path
    @app.route('/data/<path:file>')
    def get_data(file):
        return send_from_directory(app.config['data_path'], file)

    # add obscured eval data path
    @app.route('/data/truth/<int:task_id>.mp3')
    def get_eval_audio(task_id):
        audio_path = '%d_audio.mp3' % app.config['tasks'][task_id]['truth']
        return send_from_directory(app.config['data_path'], audio_path)

    # add landing page
    @app.route('/')
    def render_intro():
        return render_template('intro.html', eval_name=app.config['name'])

    # add landing page
    @app.route('/thanks')
    def render_thanks():
        return render_template('thanks.html')

    # configure blueprints
    app.register_blueprint(auth.bp)
    app.register_blueprint(examples.bp)
    app.register_blueprint(evaluation.bp)

    return app

if __name__ == '__main__':
    app = create_app()
    app.run(debug=True)

app/blueprints/auth.py
import json, os, random, string, time

from flask import Blueprint, current_app, redirect, render_template, request, session, url_for
from werkzeug.security import generate_password_hash

bp = Blueprint('auth', __name__, url_prefix='/auth')

def gen_uid():
    chars = string.ascii_letters + string.digits
    uid = ''.join(random.choice(chars) for _ in range(16))
    # intialise results as list of Nones
    json_path = os.path.join(current_app.config['result_path'], '%s.json' % uid)
    with open(json_path, 'w', encoding='utf8') as fop:
        json.dump([None for _ in range(len(current_app.config['tasks']))], fop)
    return uid

def is_valid_uid(uid):
    if not isinstance(uid, str):
        return False
    json_path = os.path.join(current_app.config['result_path'], '%s.json' % uid)
    # check if file exists
    file_exists = os.path.isfile(json_path)
    if not file_exists:
        return False
    # check if file was modified less than 10 minutes ago
    uid_last_modified = os.path.getmtime(json_path)
    session_active = (time.time() - uid_last_modified) <= 60 * 10
    return file_exists and session_active

@bp.route('/login', methods=('GET', 'POST'))
def login():
    # check if already logged in
    uid = session.get('uid', None)
    if is_valid_uid(uid):
        return redirect(url_for('index'))
    # check for code submission 
    error = False
    if request.method == 'POST':
        code = request.form['code']
        # if code matches, init session
        if code.lower() == current_app.config['code'].lower():
            session.clear()
            session['uid'] = gen_uid()
            return redirect(url_for('index'))
        else:
            error = True
    # render if not logged in or on error
    return render_template('auth.html', error=error)

@bp.before_app_request
def check_auth():
    if request.endpoint not in ['auth.login', 'static']:
        uid = session.get('uid', None)
        if not is_valid_uid(uid):
            return redirect(url_for('auth.login'))

app/blueprints/evaluation.py
import json, os, random

from flask import Blueprint, current_app, redirect, render_template, request, session, url_for

bp = Blueprint('evaluation', __name__, url_prefix='/evaluation')

def load_user_choices(uid):
    json_path = os.path.join(current_app.config['result_path'], '%s.json' % uid)
    with open(json_path, 'r', encoding='utf8') as fop:
        return json.load(fop)

def save_user_choices(uid, user_choices):
    json_path = os.path.join(current_app.config['result_path'], '%s.json' % uid)
    with open(json_path, 'w', encoding='utf8') as fop:
        json.dump(user_choices, fop)

@bp.route('/<int:page>', methods=('GET','POST'))
def index(page):
    error = None
    # sanity check
    total_pages = len(current_app.config['tasks'])
    if (page < 0) or (page >= total_pages):
        return "Evaluation task is out of range.", 404
    # retrieve  uid
    uid = session.get('uid', None)
    if uid is None:
        return "Could not retrieve UID.", 500
    # load user choices
    user_choices = load_user_choices(uid)
    # process choice submission
    if request.method == 'POST':
        # check if choice was made
        if 'choice' in request.form:
            choice_idx = request.form['choice']
            user_choices[page] = int(choice_idx)
            save_user_choices(uid, user_choices)
            # direct to next page or end
            page += 1
            if page >= total_pages:
                return redirect(url_for('thanks'))
            else:
                return redirect(url_for('evaluation.index', page=page))
        else:
            error = "Don't forget to make a selection!"
    choice_idx = user_choices[page]
    # build evaluation page
    classes = current_app.config['classes']
    options = current_app.config['tasks'][page]['options']
    order = [i for i in range(len(options))]
    random.shuffle(order)
    classes = [classes[i] for i in order]
    options = [options[i] for i in order]
    return render_template('evaluation.html', error=error, classes=classes, options=options, choice_idx=choice_idx, page=page, total_pages=total_pages)

app/blueprints/examples.py
from flask import Blueprint, render_template, current_app

bp = Blueprint('examples', __name__, url_prefix='/examples')

@bp.route('/')
def index():
    example_idcs = current_app.config['examples']
    classes = current_app.config['classes']
    return render_template('examples.html', classes=classes, example_idcs=example_idcs)

app/templates/auth.html
{% extends 'base.html' %}

{% block title %}Login{% endblock %}

{% block content %}
{% if error %}
<div class="info-box">
    Not quite right, sorry :/
</div>
{% endif %}
<form class="login-box centered" method="post" onsubmit="this.disabled=true;">
    "When are <input type="text" name="code" placeholder=""> going to take over the world?"<br>
    <br>
    <button class="button" type="submit" value="Submit">Take Over</button>
</form>
{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>{% block title %}{% endblock %} | SynVAE Eval</title>
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='main.css') }}">
    </head>
    <script type="text/javascript">
        var context = null;
    </script>
    <header>
        <h1>SynVAE <span>Evaluation</span></h1>
    </header>
    <body>
        {% block content %}{% endblock %}
    </body>
    <script type="text/javascript" src="{{ url_for('static', filename='main.js') }}"></script>
</html>

app/templates/evaluation.html
{% extends 'base.html' %}

{% block title %}Evaluation{% endblock %}

{% block content %}
<div class="info-box">
    {% if error %}
    <strong>{{ error }}</strong><br>
    {% endif %}
    Choose the image which was used to generate the audio.<br>
    <small>[space]: play &nbsp;&nbsp;|&nbsp;&nbsp; [1] - [{{ options|length }}]: select &nbsp;&nbsp;|&nbsp;&nbsp; [enter]: next</small>
</div>
<form id="options" class="option-box" method="post" onsubmit="this.disabled=true;">
    {% for idx in range(options|length) %}
    <div class="datum{{ ' selected' if options[idx] == choice_idx else ''}}" onclick="selectOption({{loop.index0}});">
        <img src="{{ url_for('data', file=(options[idx]|string)+'_orig.png') }}" alt="{{classes[idx]}}"></img>
        <input type="radio" name="choice" value="{{options[idx]}}"{{ ' checked' if options[idx] == choice_idx else ''}}>
    </div>
    {% endfor %}
</form>
<audio controls>
    <source src="{{ url_for('eval_audio', task_id=page) }}" type="audio/wav">
</audio>
<div class="navigation-bar">
    {% if page < 1 %}
    <a class="button" href="{{ url_for('examples.index') }}">Back</a>
    {% else %}
    <a class="button" href="{{page - 1}}">Back</a>
    {% endif %}
    <span class="progress-bar">
        <div style="width: {{ (page * 100)/total_pages }}%"></div>
    </span>
    <button class="button" type="submit" value="Submit" form="options">Next</button>
</div>
<script type="text/javascript">
    context = 'eval';
</script>
{% endblock %}

app/templates/examples.html
{% extends 'base.html' %}

{% block title %}Examples{% endblock %}

{% block content %}
<div class="info-box">
    Click an image to hear the corresponding audio or <a href="#" onclick="playAllAudios(0);">play all</a>.<br>
    <small>Listen a couple times to make sure you get the hang of it and can identify any patterns.</small>
</div>
<div class="example-box">
    {% for idx in example_idcs %}
    <div class="datum" onclick="playPairedAudio(this);">
        <img src="{{ url_for('data', file=(idx|string)+'_orig.png') }}" alt="{{ classes[(loop.index0 / ((example_idcs|length)/(classes|length)))|round(method='floor')|int] }}"></img>
        <audio>
            <source src="{{ url_for('data', file=(idx|string)+'_audio.wav') }}" type="audio/wav">
        </audio>
    </div>
    {% if (loop.index % ((example_idcs|length)/(classes|length))) == 0 %}
    <br>
    {% endif %}
    {% endfor %}
</div>
<div class="main-button-box">
    <a class="button" href="{{ url_for('evaluation.index', page=0) }}">
        Continue
    </a>
</div>
{% endblock %}

app/templates/intro.html
{% extends 'base.html' %}

{% block title %}Welcome{% endblock %}

{% block content %}
<div class="text-box">
    <h2>Welcome</h2>
    <p>
        Thank you very much for participating in the "{{ eval_name }}" evaluation of SynVAE.
    </p>
    <p>
        In this research project, we are trying to automatically translate images into music using a machine learning model. It tries to find a musical "language" so that similar looking images should also translate into similar sounding music. For example, this might mean that green images translate into fast music and purple images into slow music. When presented with a piece of slow music, we can then be fairly certain that its corresponding image is more purple than green.
    </p>
    <p>
        The evaluation process is pretty straightforward and should only take about 10 minutes:
        <ol>
            <li>First, we'll look at some example images and the music that was generated based on them. Keep in mind that this might not match your intuitions since everyone has very different ideas of what an image actually should sound like.</li>
            <li>Next, we'll present you with one audio and a selection of images. Your task will be to choose the image which you think the model has used as "inspiration".</li>
        </ol>
    </p>
    <p>
        Please make sure you have enough time to complete the evaluation in one go since a session automatically ends after 10 minutes of inactivity. Also, check now whether you can hear the example audio below and adjust your device's volume if necessary.
    </p>
    <p style="text-align: center;">
        <audio controls>
            <source src="{{ url_for('static', filename='example.wav') }}" type="audio/wav">
            Your browser does not seem to support audio playback.
        </audio>
    </p>
    <p>
        During the evaluation, a session cookie will help keep track of progress. As for your responses, they will be stored anonymously and since we don't record anything besides the actual responses, no data will be directly traceable to you.
    </p>
    {% if eval_disclaimer %}
    <p>
        {{ eval_disclaimer }}
    </p>
    {% endif %}
    <p>
        If you agree with the procedure and terms above, let's begin!
    </p>
    <div class="main-button-box">
        <a class="button" href="{{ url_for('examples.index') }}">
            Start
        </a>
    </div>
</div>
{% endblock %}

app/templates/thanks.html
{% extends 'base.html' %}

{% block title %}Thanks{% endblock %}

{% block content %}
<div class="text-box">
    <h2>Thank You</h2>
    <p>
        That's it! Thank you very much for participating in our evaluation.
    </p>
    {% if accuracy %}
    <p>
        Your final score is {{ accuracy*100 }}%.
        {% if accuracy >= 0.8 %}
            Wow, that's almost perfect! Nice work!
        {% elif accuracy >= 0.5 %}
            Nice work! This will help us improve the model to be even better in the future :)
        {% else %}
            Don't worry about it! This will help us improve the model in the future :)
        {% endif %}
    </p>
    {% endif %}
</div>
{% endblock %}